# Generated by Django 5.2.17 on 2026-09-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0076_initial'),
        ('SesionesKinesicas', '0008_initial'),
        ('clinicas', '0005_add_secretaria_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_sesion_default', models.DecimalField(decimal_places=0, default=0, help_text='Se autocompleta al registrar pagos individuales.', max_digits=10, verbose_name='Precio default por sesión ($)')),
                ('alerta_deuda_activa', models.BooleanField(default=True, verbose_name='Mostrar alerta de deuda en ficha')),
                ('dias_tolerancia_bono', models.PositiveIntegerField(default=7, help_text='Si el bono no llega en este plazo, se marca como deuda.', verbose_name='Días de tolerancia para entrega de bono')),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_pagos', to='clinicas.clinica', verbose_name='Clínica')),
            ],
            options={
                'verbose_name': 'Configuración de Pagos',
                'verbose_name_plural': 'Configuraciones de Pagos',
            },
        ),
        migrations.CreateModel(
            name='PackAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pack 10 sesiones, Pack mensual', max_length=100, verbose_name='Nombre del pack')),
                ('total_sesiones', models.PositiveIntegerField(verbose_name='Total de sesiones incluidas')),
                ('sesiones_usadas', models.PositiveIntegerField(default=0, verbose_name='Sesiones consumidas')),
                ('precio_total', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Precio total del pack ($)')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Opcional. Si vence, las sesiones restantes quedan expiradas.', null=True, verbose_name='Fecha de vencimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('agotado', 'Agotado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='activo', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs_atencion', to='clinicas.clinica', verbose_name='Clínica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs_atencion', to='Login.paciente', verbose_name='Paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs_registrados', to='Login.clinico', verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pack de Atención',
                'verbose_name_plural': 'Packs de Atención',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio_pago', models.CharField(choices=[('bono_fonasa', 'Bono Fonasa'), ('bono_isapre', 'Bono Isapre'), ('particular_efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta Débito/Crédito'), ('convenio', 'Convenio / Cortesía'), ('pack', 'Descontado del Pack')], max_length=30, verbose_name='Medio de pago')),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto ($)')),
                ('folio_bono', models.CharField(blank=True, default='', help_text='Número de folio del bono Fonasa o Isapre', max_length=50, verbose_name='Folio / N° bono')),
                ('comprobante', models.CharField(blank=True, default='', help_text='N° de transferencia, voucher, etc.', max_length=100, verbose_name='Referencia / Comprobante')),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente'), ('bono_por_llegar', 'Bono por llegar'), ('anulado', 'Anulado')], default='pagado', max_length=20, verbose_name='Estado del pago')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pago', to='clinicas.clinica', verbose_name='Clínica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_pago', to='Login.paciente', verbose_name='Paciente')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_descontados', to='pagos.packatencion', verbose_name='Pack asociado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to='Login.clinico', verbose_name='Registrado por')),
                ('sesion_kinesica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_pago', to='SesionesKinesicas.sesionkinesica', verbose_name='Sesión kinésica asociada')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pago',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DeudaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesiones_sin_pago', models.PositiveIntegerField(default=0, verbose_name='Sesiones sin pago')),
                ('monto_pendiente', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto pendiente ($)')),
                ('bonos_por_llegar', models.PositiveIntegerField(default=0, verbose_name='Bonos por recibir')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_pacientes', to='clinicas.clinica', verbose_name='Clínica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deuda_resumen', to='Login.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Deuda de Paciente',
                'verbose_name_plural': 'Deudas de Pacientes',
                'indexes': [models.Index(fields=['clinica', 'sesiones_sin_pago'], name='pagos_deuda_clinica_f1b2de_idx')],
                'unique_together': {('paciente', 'clinica')},
            },
        ),
        migrations.AddIndex(
            model_name='packatencion',
            index=models.Index(fields=['paciente', 'estado'], name='pagos_packa_pacient_2a680b_idx'),
        ),
        migrations.AddIndex(
            model_name='packatencion',
            index=models.Index(fields=['clinica', '-fecha_compra'], name='pagos_packa_clinica_d64d50_idx'),
        ),
        migrations.AddIndex(
            model_name='registropago',
            index=models.Index(fields=['paciente', '-fecha_registro'], name='pagos_regis_pacient_79821d_idx'),
        ),
        migrations.AddIndex(
            model_name='registropago',
            index=models.Index(fields=['clinica', '-fecha_registro'], name='pagos_regis_clinica_a912ca_idx'),
        ),
        migrations.AddIndex(
            model_name='registropago',
            index=models.Index(fields=['sesion_kinesica'], name='pagos_regis_sesion__77e5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='registropago',
            index=models.Index(fields=['estado'], name='pagos_regis_estado_4f8d44_idx'),
        ),
    ]
