# Generated by Django 5.2.17 on 2026-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropago',
            name='adjunto',
            field=models.ImageField(blank=True, help_text='Imagen del voucher, pantallazo de transferencia, etc.', null=True, upload_to='pagos/adjuntos/%Y/%m/', verbose_name='Adjunto (voucher / comprobante)'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='comprobante_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Referencia segundo pago'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='medio_pago_2',
            field=models.CharField(blank=True, choices=[], default='', max_length=30, verbose_name='Segundo medio de pago (pago mixto)'),
        ),
        migrations.AddField(
            model_name='registropago',
            name='monto_2',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Monto segundo medio ($)'),
        ),
    ]
