# Generated by Django 5.2.7 on 2025-10-21 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0063_alter_clinico_options_clinico_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFormulario',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('paciente_rut', models.CharField(blank=True, help_text='RUT del paciente que usó el token', max_length=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_formulario', to='Login.clinico')),
            ],
            options={
                'verbose_name': 'Token de Formulario',
                'verbose_name_plural': 'Tokens de Formulario',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
