# Generated by Django 5.2.7 on 2025-10-21 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioInicial', '0001_initial'),
        ('Login', '0063_alter_clinico_options_clinico_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenformulario',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Token de Formulario', 'verbose_name_plural': 'Tokens de Formularios'},
        ),
        migrations.RemoveField(
            model_name='tokenformulario',
            name='paciente_rut',
        ),
        migrations.RemoveField(
            model_name='tokenformulario',
            name='token',
        ),
        migrations.AddField(
            model_name='tokenformulario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tokenformulario',
            name='paciente_asociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_formulario', to='Login.paciente'),
        ),
    ]
