# Generated by Django 5.2.8 on 2026-04-28 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioInicial', '0002_alter_tokenformulario_options_and_more'),
        ('Login', '0064_paciente_correo_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenformulario',
            name='paciente_asociado',
        ),
        migrations.AddField(
            model_name='tokenformulario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens_formulario', to='Login.paciente'),
        ),
    ]
