# Generated by Django 5.2.15 on 2026-06-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormularioInicial', '0003_remove_tokenformulario_paciente_asociado_and_more'),
        ('Login', '0066_reserva_indexes'),
        ('clinicas', '0004_clinica_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('formulario_qr', 'Formulario QR'), ('alta_panel', 'Alta en panel')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicas.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='Login.paciente')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='FormularioInicial.tokenformulario')),
            ],
            options={
                'verbose_name': 'Consentimiento de datos',
                'verbose_name_plural': 'Consentimientos de datos',
                'ordering': ['-fecha'],
            },
        ),
    ]
