# Generated by Django 5.1.4 on 2024-12-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioIncial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('telefono', models.CharField(max_length=12)),
                ('cobertura_de_salud', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinico',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('pacientes', models.ManyToManyField(related_name='clinico', to='Login.paciente')),
            ],
        ),
    ]
