# Generated by Django 5.1.4 on 2024-12-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioInicial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='FormularioIncial',
        ),
        migrations.AlterField(
            model_name='clinico',
            name='pacientes',
            field=models.ManyToManyField(related_name='Clinico', to='Login.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='formularioIni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.formularioinicial'),
        ),
    ]
