# Generated by Django 5.1.4 on 2025-01-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_formularioinicial_delete_formularioincial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='formularioIni',
        ),
        migrations.RemoveField(
            model_name='clinico',
            name='sexo',
        ),
        migrations.AddField(
            model_name='clinico',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='pacientes',
            field=models.ManyToManyField(related_name='clinicos', to='Login.paciente'),
        ),
        migrations.DeleteModel(
            name='FormularioInicial',
        ),
    ]
