# Generated by Django 5.1.4 on 2025-01-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_remove_paciente_formularioini_remove_clinico_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='profesion',
            field=models.CharField(default='default_profession', max_length=50),
        ),
    ]
