# Generated by Django 5.1.4 on 2025-01-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_clinico_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='es_superusuario',
            field=models.BooleanField(default=False),
        ),
    ]
