# Generated by Django 5.1.4 on 2025-01-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_clinico_es_superusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinico',
            name='es_superusuario',
        ),
    ]
