# Generated by Django 5.1.4 on 2025-01-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_remove_clinico_es_superusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='formularioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('curacionDolor', models.CharField(max_length=20)),
                ('caracteristicasDeDolor', models.JSONField()),
                ('causaDolor', models.CharField(max_length=50)),
                ('accidenteLaboral', models.JSONField()),
                ('calidadAtencion', models.TextField(blank=True, null=True)),
                ('opinionProblemaEnfermeda', models.CharField(max_length=20)),
                ('opinionCuraDolor', models.CharField(max_length=20)),
                ('dificultadActividad', models.TextField(blank=True, null=True)),
                ('rangoDificultad', models.IntegerField()),
                ('nesesidadDeApoyo', models.BooleanField()),
                ('TiposDeEnfermedades', models.JSONField()),
                ('mencionesActividades', models.JSONField()),
                ('dolorIntensidad', models.JSONField()),
                ('IntensidadDolor', models.IntegerField()),
                ('preguntas1', models.JSONField()),
                ('preguntas2', models.JSONField()),
                ('pregunta1_nivelDeSalud', models.IntegerField()),
                ('pregunta2_horas_de_sueño_en_promedio', models.CharField(max_length=30)),
                ('pregunta3_frecuencia_De_Suenio', models.CharField(max_length=30)),
                ('pregunta4_opinion_peso_actual', models.CharField(max_length=30)),
                ('pregunta5_ConsumoComidaRapida', models.CharField(max_length=30)),
                ('pregunta6_PorcionesDeFrutas', models.CharField(max_length=30)),
                ('pregunta7_ejercicioDias', models.CharField(max_length=30)),
                ('pregunta8_minutosPorEjercicios', models.CharField(max_length=30)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='Login.clinico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='Login.paciente')),
            ],
        ),
    ]
