# Generated by Django 5.1.4 on 2025-01-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_remove_paciente_sexo_paciente_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono',
            new_name='contacto',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
