# Generated by Django 5.1.4 on 2025-01-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_rename_telefono_paciente_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='curacionDolor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
