# Generated by Django 5.1.4 on 2025-01-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_formularioclinico_curaciondolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='IntensidadDolor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='TiposDeEnfermedades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='accidenteLaboral',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='causaDolor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='dolorIntensidad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='mencionesActividades',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='nesesidadDeApoyo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='opinionCuraDolor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='opinionProblemaEnfermeda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta1_nivelDeSalud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta2_horas_de_sueño_en_promedio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta3_frecuencia_De_Suenio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta4_opinion_peso_actual',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta5_ConsumoComidaRapida',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta6_PorcionesDeFrutas',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta7_ejercicioDias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta8_minutosPorEjercicios',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='preguntas1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='preguntas2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='rangoDificultad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
