# Generated by Django 5.1.4 on 2025-01-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_alter_formularioclinico_intensidaddolor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='accidenteLaboral',
            new_name='dolorSenial',
        ),
    ]
