# Generated by Django 5.1.4 on 2025-01-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_rename_accidentelaboral_formularioclinico_dolorsenial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='dolorSenial',
            new_name='accidenteLaboral',
        ),
    ]
