# Generated by Django 5.1.4 on 2025-01-10 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_rename_dolorsenial_formularioclinico_accidentelaboral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='IntensidadDolor',
            new_name='DuracionDolor',
        ),
    ]
