# Generated by Django 5.1.4 on 2025-01-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_rename_intensidaddolor_formularioclinico_duraciondolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='nesesidadDeApoyo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
