# Generated by Django 5.1.4 on 2025-01-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_alter_formularioclinico_nesesidaddeapoyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta2_horas_de_sueño_en_promedio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta3_frecuencia_De_Suenio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta4_opinion_peso_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta5_ConsumoComidaRapida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta6_PorcionesDeFrutas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta7_ejercicioDias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta8_minutosPorEjercicios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
