# Generated by Django 5.1.4 on 2025-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0016_alter_formularioclinico_pregunta2_horas_de_sueño_en_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta3_frecuencia_De_Suenio',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta4_opinion_peso_actual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta5_ConsumoComidaRapida',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta6_PorcionesDeFrutas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta7_ejercicioDias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta8_minutosPorEjercicios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
