# Generated by Django 5.1.4 on 2025-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0017_alter_formularioclinico_pregunta3_frecuencia_de_suenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta2_horas_de_sueño_en_promedio',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
