# Generated by Django 5.1.4 on 2025-01-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0018_alter_formularioclinico_pregunta2_horas_de_sueño_en_promedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioclinico',
            name='ubicacionDolor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
