# Generated by Django 5.1.4 on 2025-01-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0019_formularioclinico_ubicaciondolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioclinico',
            name='AreasMotivacion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='DrograsPreocupacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='NicotinaSiOno',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='ansioso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='cigarroPreocupacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='cigarroSiOno',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='condicionDrogas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='condicionMarihuana',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='condicionNicotina',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='condicioncigarro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='deprimido',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='drogasSiOno',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='marihuanaPreocupacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='marihuanaSiOno',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='medicamento_efectivo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='medicamentos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='motivacion_Salud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='nicotinaPreocupacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='placer_cosas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='preocupacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='proposito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formularioclinico',
            name='red_de_apoyo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
