# Generated by Django 5.1.4 on 2025-01-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0020_formularioclinico_areasmotivacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='medicamento_efectivo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
