# Generated by Django 5.1.4 on 2025-01-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0022_rename_drograspreocupacion_formularioclinico_alcoholpreocupacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='EsAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
