# Generated by Django 5.1.4 on 2025-01-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0023_clinico_esadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinico',
            name='EsAdmin',
        ),
    ]
