# Generated by Django 5.1.4 on 2025-01-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0024_remove_clinico_esadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='EsAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
