# Generated by Django 5.1.5 on 2025-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0026_alter_formularioclinico_alcoholpreocupacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='DuracionDolor',
            new_name='IntensidadDolor',
        ),
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='medicamento_efectivo',
            new_name='actividades_afectadas',
        ),
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='curacionDolor',
            new_name='duracionDolor',
        ),
        migrations.RenameField(
            model_name='formularioclinico',
            old_name='mencionesActividades',
            new_name='parametros',
        ),
        migrations.RemoveField(
            model_name='formularioclinico',
            name='dificultadActividad',
        ),
        migrations.RemoveField(
            model_name='formularioclinico',
            name='rangoDificultad',
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta1_nivelDeSalud',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta2_horas_de_sueño_en_promedio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta3_frecuencia_De_Suenio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta4_opinion_peso_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta5_ConsumoComidaRapida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta6_PorcionesDeFrutas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta7_ejercicioDias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formularioclinico',
            name='pregunta8_minutosPorEjercicios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
