# Generated by Django 5.1.5 on 2025-01-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0027_rename_duraciondolor_formularioclinico_intensidaddolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioclinico',
            name='IntensidadDolor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
