# Generated by Django 5.1.5 on 2025-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0028_alter_formularioclinico_intensidaddolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField()),
            ],
        ),
    ]
