# Generated by Django 5.1.5 on 2025-01-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0030_alter_paciente_fechanacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profesion',
            field=models.CharField(default='Sin profesion', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='trabajo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
