# Generated by Django 5.1.5 on 2025-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0032_remove_formularioclinico_pregunta2_horas_de_sueño_en_promedio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='profesion',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='trabajo',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
