# Generated by Django 5.1.5 on 2025-02-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0034_alter_paciente_profesion_alter_paciente_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('notas', models.TextField(blank=True, null=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
            ],
        ),
    ]
