# Generated by Django 5.1.5 on 2025-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0035_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='LicenciaDias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='LicenciaFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='LicenciaInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
