# Generated by Django 5.1.5 on 2025-02-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0036_paciente_licenciadias_paciente_licenciafin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioPSFS',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField()),
                ('puntaje_actividad_1', models.IntegerField(blank=True, null=True)),
                ('puntaje_actividad_2', models.IntegerField(blank=True, null=True)),
                ('puntaje_actividad_3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
