# Generated by Django 5.1.5 on 2025-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0037_cuestionariopsfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionariopsfs',
            name='puntaje_actividad_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariopsfs',
            name='puntaje_actividad_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariopsfs',
            name='puntaje_actividad_3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
