# Generated by Django 5.1.5 on 2025-02-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0038_alter_cuestionariopsfs_puntaje_actividad_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groc',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField()),
                ('puntajeGroc', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
