# Generated by Django 5.1.5 on 2025-02-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0039_groc'),
    ]

    operations = [
        migrations.AddField(
            model_name='groc',
            name='NotaGroc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
