# Generated by Django 5.1.5 on 2025-02-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0040_groc_notagroc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groc',
            name='NotaGroc',
        ),
    ]
