# Generated by Django 5.1.5 on 2025-02-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0042_groc_notagroc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariopsfs',
            name='NotaCuestionarioPSFS',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuestionariopsfs',
            name='puntajeTotal',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
