# Generated by Django 5.1.5 on 2025-02-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0043_cuestionariopsfs_notacuestionariopsfs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioEQ_5D',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('movilidad', models.TextField(blank=True, null=True)),
                ('cuidado_personal', models.TextField(blank=True, null=True)),
                ('actividades_cotidianas', models.TextField(blank=True, null=True)),
                ('dolor_malestar', models.TextField(blank=True, null=True)),
                ('ansiedad_depresion', models.TextField(blank=True, null=True)),
                ('puntaje_movilidad', models.IntegerField(blank=True, null=True)),
                ('puntaje_cuidado_personal', models.IntegerField(blank=True, null=True)),
                ('puntaje_actividades_cotidianas', models.IntegerField(blank=True, null=True)),
                ('puntaje_dolor_malestar', models.IntegerField(blank=True, null=True)),
                ('puntaje_ansiedad_depresion', models.IntegerField(blank=True, null=True)),
                ('vas_score', models.IntegerField(blank=True, null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuestionarioEQ_5D', to='Login.clinico')),
            ],
        ),
    ]
