# Generated by Django 5.1.5 on 2025-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0044_cuestionarioeq_5d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_actividades_cotidianas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_ansiedad_depresion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_cuidado_personal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_dolor_malestar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_movilidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='vas_score',
            field=models.IntegerField(default=0),
        ),
    ]
