# Generated by Django 5.1.5 on 2025-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0045_alter_cuestionarioeq_5d_puntaje_actividades_cotidianas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='actividades_cotidianas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='ansiedad_depresion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='cuidado_personal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='dolor_malestar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='movilidad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_actividades_cotidianas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_ansiedad_depresion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_cuidado_personal',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_dolor_malestar',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='puntaje_movilidad',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionarioeq_5d',
            name='vas_score',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
