# Generated by Django 5.2.5 on 2025-08-10 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0046_alter_cuestionarioeq_5d_actividades_cotidianas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioBarthel',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('comer', models.IntegerField(choices=[(10, 'Totalmente independiente'), (5, 'Necesita ayuda para cortar carne, pan, etc.'), (0, 'Dependiente')])),
                ('lavarse', models.IntegerField(choices=[(5, 'Independiente (entra y sale solo del baño)'), (0, 'Dependiente')])),
                ('vestirse', models.IntegerField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda'), (0, 'Dependiente')])),
                ('arreglarse', models.IntegerField(choices=[(5, 'Independiente'), (0, 'Dependiente')])),
                ('deposiciones', models.IntegerField(choices=[(10, 'Continencia normal'), (5, 'Ocasionalmente algún episodio / necesita ayuda'), (0, 'Incontinencia')])),
                ('miccion', models.IntegerField(choices=[(10, 'Continencia normal o cuida su sonda'), (5, 'Máximo 1 episodio diario o necesita ayuda'), (0, 'Incontinencia')])),
                ('usar_retrete', models.IntegerField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda pero se limpia solo'), (0, 'Dependiente')])),
                ('trasladarse', models.IntegerField(choices=[(15, 'Independiente'), (10, 'Mínima ayuda o supervisión'), (5, 'Gran ayuda pero se mantiene sentado solo'), (0, 'Dependiente')])),
                ('deambular', models.IntegerField(choices=[(15, 'Independiente, camina solo 50m'), (10, 'Necesita ayuda o supervisión para caminar 50m'), (5, 'Independiente en silla de ruedas'), (0, 'Dependiente')])),
                ('escalones', models.IntegerField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda'), (0, 'Dependiente')])),
                ('puntaje_total', models.IntegerField(blank=True, null=True)),
                ('grado_dependencia', models.CharField(blank=True, max_length=20, null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios_barthel', to='Login.clinico')),
            ],
        ),
    ]
