# Generated by Django 5.2.5 on 2025-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0047_cuestionariobarthel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='contacto',
            field=models.CharField(max_length=13),
        ),
    ]
