# Generated by Django 5.2.5 on 2025-08-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0048_alter_paciente_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='arreglarse',
            field=models.JSONField(choices=[(5, 'Independiente'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='comer',
            field=models.JSONField(choices=[(10, 'Totalmente independiente'), (5, 'Necesita ayuda para cortar carne, pan, etc.'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='deambular',
            field=models.JSONField(choices=[(15, 'Independiente, camina solo 50m'), (10, 'Necesita ayuda o supervisión para caminar 50m'), (5, 'Independiente en silla de ruedas'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='deposiciones',
            field=models.JSONField(choices=[(10, 'Continencia normal'), (5, 'Ocasionalmente algún episodio / necesita ayuda'), (0, 'Incontinencia')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='escalones',
            field=models.JSONField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='grado_dependencia',
            field=models.JSONField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='lavarse',
            field=models.JSONField(choices=[(5, 'Independiente (entra y sale solo del baño)'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='miccion',
            field=models.JSONField(choices=[(10, 'Continencia normal o cuida su sonda'), (5, 'Máximo 1 episodio diario o necesita ayuda'), (0, 'Incontinencia')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='puntaje_total',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='trasladarse',
            field=models.JSONField(choices=[(15, 'Independiente'), (10, 'Mínima ayuda o supervisión'), (5, 'Gran ayuda pero se mantiene sentado solo'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='usar_retrete',
            field=models.JSONField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda pero se limpia solo'), (0, 'Dependiente')]),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='vestirse',
            field=models.JSONField(choices=[(10, 'Independiente'), (5, 'Necesita ayuda'), (0, 'Dependiente')]),
        ),
    ]
