# Generated by Django 5.2.5 on 2025-08-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0049_alter_cuestionariobarthel_arreglarse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariobarthel',
            name='NotaCuestionarioBarthel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='arreglarse',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='comer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='deambular',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='deposiciones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='escalones',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='grado_dependencia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='lavarse',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='miccion',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='trasladarse',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='usar_retrete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuestionariobarthel',
            name='vestirse',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
