# Generated by Django 5.2.5 on 2025-08-22 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0050_cuestionariobarthel_notacuestionariobarthel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioScrenning',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('IntensidadDolor', models.TextField(blank=True, null=True)),
                ('RespuestasTabla1', models.JSONField(blank=True, null=True)),
                ('nesesidadDeApoyo', models.CharField(blank=True, max_length=20, null=True)),
                ('NotaCuestionarioScrenning', models.TextField(blank=True, null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios_screnning', to='Login.clinico')),
            ],
        ),
    ]
