# Generated by Django 5.2.5 on 2025-08-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0051_cuestionarioscrenning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioclinico',
            name='IntensidadDolor',
        ),
        migrations.RemoveField(
            model_name='formularioclinico',
            name='nesesidadDeApoyo',
        ),
        migrations.RemoveField(
            model_name='formularioclinico',
            name='preguntas1',
        ),
    ]
