# Generated by Django 5.2.5 on 2025-08-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0052_remove_formularioclinico_intensidaddolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionarioscrenning',
            name='NotaCuestionarioScrenning',
        ),
        migrations.CreateModel(
            name='CuestionarioEvaluacionENA',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado_por_sesion', models.JSONField(blank=True, null=True)),
                ('NotaCuestionarioEvaluacionENA', models.TextField(blank=True, null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios_evaluacion_ena', to='Login.clinico')),
            ],
        ),
    ]
