# Generated by Django 5.2.5 on 2025-08-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0053_remove_cuestionarioscrenning_notacuestionarioscrenning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinico',
            name='contraseña',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AlterField(
            model_name='cuestionarioscrenning',
            name='IntensidadDolor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
