# Generated by Django 5.2.5 on 2025-08-29 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0054_alter_clinico_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinico',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_asignados', to='Login.clinico'),
        ),
    ]
