# Generated by Django 5.2.5 on 2025-08-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0055_remove_clinico_pacientes_remove_paciente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
