# Generated by Django 5.2.5 on 2025-09-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0056_paciente_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionarioevaluacionena',
            name='puntaje_obtenido_sesion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
