# Generated by Django 5.2.5 on 2025-09-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0057_cuestionarioevaluacionena_puntaje_obtenido_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuestionarioscrenning',
            name='nesesidadDeApoyo',
        ),
        migrations.AddField(
            model_name='cuestionarioscrenning',
            name='NivelMolestia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuestionarioscrenning',
            name='Nota_CuestionarioScrenning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuestionarioscrenning',
            name='Puntaje_Sesion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
