# Generated by Django 5.2.5 on 2025-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0058_remove_cuestionarioscrenning_nesesidaddeapoyo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionariopsfs',
            name='actividad_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuestionariopsfs',
            name='actividad_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuestionariopsfs',
            name='actividad_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
