# Generated by Django 5.2.5 on 2025-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0059_cuestionariopsfs_actividad_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=14, primary_key=True, serialize=False, unique=True),
        ),
    ]
