# Generated by Django 5.2.5 on 2025-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0060_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
