# Generated by Django 5.2.5 on 2025-09-30 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0061_alter_paciente_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Login.paciente')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('NotaRecetaMedica', models.TextField(blank=True, null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_medicas', to='Login.clinico')),
            ],
        ),
    ]
