# Generated by Django 5.2.7 on 2025-10-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0062_recetamedica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinico',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Clínico', 'verbose_name_plural': 'Clínicos'},
        ),
        migrations.AddField(
            model_name='clinico',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Cuenta activa'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='centro_trabajo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro o institución de trabajo'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad o Región'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía o descripción profesional'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='experiencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='numero_registro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de registro profesional'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono profesional'),
        ),
        migrations.AddField(
            model_name='clinico',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='EsAdmin',
            field=models.BooleanField(default=False, verbose_name='Es administrador del sistema'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='contraseña',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='profesion',
            field=models.CharField(max_length=100, verbose_name='Profesión / Cargo'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT'),
        ),
    ]
