# Generated by Django 5.2.8 on 2026-04-03 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0063_alter_clinico_options_clinico_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo o Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_agendadas', to='Login.clinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='Login.paciente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
