# Generated by Django 5.2.15 on 2026-06-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0066_reserva_indexes'),
        ('clinicas', '0004_clinica_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('historial', 'Historial clínico'), ('informe', 'Informe DSS'), ('ficha', 'Ficha clínica'), ('exportar_json', 'Exportación JSON (ARCO)'), ('exportar_html', 'Exportación HTML (ARCO)')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de acceso',
                'verbose_name_plural': 'Auditorías de acceso',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='Login_reser_clinico_212467_idx',
            old_name='Login_reser_clinico_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='Login_reser_fecha_739d1d_idx',
            old_name='Login_reser_fecha_h_4c9e81_idx',
        ),
        migrations.AddField(
            model_name='auditoriaacceso',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acceso', to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='auditoriaacceso',
            name='clinico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to='Login.clinico'),
        ),
        migrations.AddField(
            model_name='auditoriaacceso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_acceso', to='Login.paciente'),
        ),
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['clinica', '-fecha'], name='Login_audit_clinica_fff01a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriaacceso',
            index=models.Index(fields=['paciente', '-fecha'], name='Login_audit_pacient_91c879_idx'),
        ),
    ]
