# Generated by Django 5.2.15 on 2026-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0070_paciente_documento_extranjero'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditoriaacceso',
            new_name='Login_audit_clinico_966c31_idx',
            old_name='Login_audit_clinico_fecha_idx',
        ),
    ]
