# Generated by Django 5.2.15 on 2026-07-22 16:32
# Reescrita idempotente: tolera migraciones parciales (Duplicate column ciclo_id).

import django.db.models.deletion
from django.db import migrations, models

from ciclos_clinicos.migration_utils import (
    add_ciclo_fk,
    column_exists,
    migrate_questionnaire_pk_to_id,
    _drop_foreign_keys_on_column,
    _restore_paciente_fk,
)


def apply_login_ciclo_schema(apps, schema_editor):
    """Aplica cambios de esquema solo si faltan (recuperación tras fallo parcial)."""
    questionnaire_tables = [
        'Login_cuestionariobarthel',
        'Login_cuestionarioeq_5d',
        'Login_cuestionarioevaluacionena',
        'Login_cuestionariopsfs',
        'Login_cuestionarioscrenning',
        'Login_groc',
    ]
    for table in questionnaire_tables:
        migrate_questionnaire_pk_to_id(schema_editor, table)

    add_ciclo_fk(schema_editor, 'Login_formularioclinico', unique=True)

    with schema_editor.connection.cursor() as cursor:
        if not column_exists(cursor, 'Login_formularioclinico', 'paciente_id'):
            return
        cursor.execute(
            """
            SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'Login_formularioclinico'
              AND COLUMN_NAME = 'paciente_id'
              AND CONSTRAINT_NAME = 'PRIMARY'
            """
        )
        if cursor.fetchone()[0] > 0:
            _drop_foreign_keys_on_column(schema_editor, 'Login_formularioclinico', 'paciente_id')
            schema_editor.execute(
                'ALTER TABLE `Login_formularioclinico` DROP PRIMARY KEY, '
                'ADD PRIMARY KEY (`id`)'
            )
            _restore_paciente_fk(schema_editor, 'Login_formularioclinico')
        else:
            _drop_foreign_keys_on_column(schema_editor, 'Login_formularioclinico', 'paciente_id')
            schema_editor.execute(
                'ALTER TABLE `Login_formularioclinico` '
                'MODIFY COLUMN `paciente_id` varchar(255) NULL'
            )
            _restore_paciente_fk(schema_editor, 'Login_formularioclinico')


def noop_reverse(apps, schema_editor):
    pass


# Operaciones de estado Django (sin tocar BD — la BD la maneja RunPython)
STATE_OPERATIONS = [
    migrations.AddField(
        model_name='cuestionariobarthel',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='barthel',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='cuestionariobarthel',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AddField(
        model_name='cuestionarioeq_5d',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='eq5d',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='cuestionarioeq_5d',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AddField(
        model_name='cuestionarioevaluacionena',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='ena',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='cuestionarioevaluacionena',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AddField(
        model_name='cuestionariopsfs',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='psfs',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='cuestionariopsfs',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AddField(
        model_name='cuestionarioscrenning',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='screening',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='cuestionarioscrenning',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AddField(
        model_name='formularioclinico',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='formulario',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='groc',
        name='ciclo',
        field=models.OneToOneField(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='groc',
            to='ciclos_clinicos.cicloclinico',
        ),
    ),
    migrations.AddField(
        model_name='groc',
        name='id',
        field=models.BigAutoField(primary_key=True, serialize=False),
    ),
    migrations.AlterField(
        model_name='auditoriaacceso',
        name='accion',
        field=models.CharField(
            choices=[
                ('consulta_historial', 'Consultó historial clínico'),
                ('edicion_nota_clinica', 'Editó notas clínicas del historial'),
                ('consulta_informe_dss', 'Visualizó informe DSS (anamnesis)'),
                ('consulta_ficha_profesional', 'Visualizó ficha clínica profesional'),
                ('consulta_resumen_paciente', 'Visualizó resumen del paciente en panel'),
                ('alta_paciente', 'Registró nuevo paciente'),
                ('edicion_paciente', 'Modificó datos demográficos del paciente'),
                ('eliminacion_paciente', 'Eliminó ficha de paciente'),
                ('exportacion_arco_json', 'Exportó ficha completa (ARCO — JSON)'),
                ('exportacion_arco_html', 'Exportó ficha completa (ARCO — HTML)'),
                ('reserva_crear', 'Creó cita / reserva'),
                ('reserva_modificar', 'Modificó cita / reserva'),
                ('reserva_eliminar', 'Eliminó cita / reserva'),
                ('exportacion_auditoria_pdf', 'Exportó registro de auditoría (PDF)'),
                ('consulta_cuestionario', 'Consultó cuestionario clínico'),
                ('edicion_cuestionario', 'Editó cuestionario clínico'),
                ('consulta_lista_sesiones_kine', 'Consultó listado de sesiones kinésicas'),
                ('consulta_sesion_kine', 'Visualizó sesión kinésica'),
                ('alta_sesion_kine', 'Registró sesión kinésica'),
                ('edicion_sesion_kine', 'Editó sesión kinésica'),
                ('consulta_receta', 'Consultó receta médica'),
                ('receta_crear', 'Creó receta médica'),
                ('receta_editar', 'Editó receta médica'),
                ('receta_eliminar', 'Eliminó receta médica'),
                ('consulta_estadisticas_centro', 'Consultó estadísticas del centro'),
                ('consulta_estadisticas_paciente', 'Consultó estadísticas del paciente'),
                ('consulta_calendario', 'Consultó agenda / calendario'),
                ('consulta_lista_pacientes', 'Consultó listado de pacientes'),
                ('qr_generar', 'Generó formulario remoto (QR)'),
                ('qr_desactivar', 'Desactivó formulario remoto (QR)'),
                ('consulta_auditoria', 'Consultó registro de auditoría'),
                ('edicion_anamnesis', 'Registró o editó anamnesis DSS'),
                ('formulario_qr_enviado', 'Paciente envió anamnesis vía formulario QR'),
                ('consulta_formulario_inicial', 'Accedió al formulario de anamnesis DSS'),
                ('inicio_ciclo_clinico', 'Inició nuevo ciclo clínico'),
                ('cierre_ciclo_clinico', 'Cerró ciclo clínico'),
                ('consulta_ciclo_historico', 'Consultó historial de ciclos clínicos'),
            ],
            max_length=40,
        ),
    ),
    migrations.AlterField(
        model_name='cuestionariobarthel',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_barthel',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='cuestionarioeq_5d',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_eq5d',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='cuestionarioevaluacionena',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_evaluacion_ena',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='cuestionariopsfs',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_psfs',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='cuestionarioscrenning',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_screnning',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='formularioclinico',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='formularios_clinicos',
            to='Login.paciente',
        ),
    ),
    migrations.AlterField(
        model_name='groc',
        name='paciente',
        field=models.ForeignKey(
            blank=True, null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name='cuestionarios_groc',
            to='Login.paciente',
        ),
    ),
]


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('Login', '0071_ciclos_clinicos_inicial'),
        ('ciclos_clinicos', '0001_ciclos_clinicos_inicial'),
    ]

    operations = [
        migrations.RunPython(apply_login_ciclo_schema, noop_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
    ]
