# Generated by Django 5.2.16 on 2026-09-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0072_ciclos_clinicos_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_atencion',
            field=models.CharField(choices=[('Consulta', 'Consulta Presencial'), ('Domicilio', 'Atención a Domicilio'), ('Telemedicina', 'Telemedicina'), ('Otro', 'Otro')], default='Consulta', max_length=20, verbose_name='Tipo de Atención'),
        ),
    ]
