# Generated by Django 5.2.17 on 2026-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0073_reserva_tipo_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='acepta_terminos_dictado',
            field=models.BooleanField(default=False, help_text='El profesional aceptó los términos de uso y privacidad del dictado por voz.', verbose_name='Aceptó términos de dictado por voz'),
        ),
    ]
