# Generated by Django 5.2.17 on 2026-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0074_acepta_terminos_dictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinico',
            name='version_novedades_leida',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Última versión de novedades leída'),
        ),
    ]
