# Generated by Django 5.2.17 on 2026-10-01 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0076_initial'),
        ('planes', '0007_suscripcionclinica_override_max_adjuntos'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Opcional. Si se define, solo este email puede usar el link.', max_length=254, null=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('plan_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planes.plan')),
            ],
            options={
                'verbose_name': 'Invitación de Registro',
                'verbose_name_plural': 'Invitaciones de Registro',
            },
        ),
    ]
