# Generated by Django 5.2.7 on 2026-04-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0064_paciente_correo_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionKinesica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveIntegerField(help_text='Número secuencial de la sesión', verbose_name='Número de Sesión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('evaluacion_inicial', models.JSONField(blank=True, help_text='Cuestionario detallado de la primera sesión', null=True, verbose_name='Evaluación Inicial')),
                ('notas_clinicas', models.TextField(blank=True, help_text='Notas clínicas del clínico sobre el paciente', null=True, verbose_name='Notas Clínicas')),
                ('evolucion', models.TextField(blank=True, help_text='Descripción de la evolución del paciente en esta sesión', null=True, verbose_name='Evolución')),
                ('es_primera_sesion', models.BooleanField(default=False, verbose_name='Es Primera Sesión')),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_kinesicas_realizadas', to='Login.clinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_kinesicas', to='Login.paciente')),
            ],
            options={
                'verbose_name': 'Sesión Kinésica',
                'verbose_name_plural': 'Sesiones Kinésicas',
                'ordering': ['-numero_sesion'],
                'indexes': [models.Index(fields=['paciente', '-numero_sesion'], name='SesionesKin_pacient_7387e2_idx'), models.Index(fields=['clinico', 'fecha_creacion'], name='SesionesKin_clinico_717fb4_idx')],
                'unique_together': {('paciente', 'numero_sesion')},
            },
        ),
    ]
