# Generated by Django 5.2.8 on 2026-04-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SesionesKinesicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionkinesica',
            name='diagnostico_final',
            field=models.TextField(blank=True, help_text='Diagnóstico kinésico al cierre del tratamiento', null=True, verbose_name='Diagnóstico Kinésico Final'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='es_sesion_final',
            field=models.BooleanField(default=False, verbose_name='Es Sesión Final'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='estado_al_alta',
            field=models.CharField(blank=True, choices=[('mejorado', 'Mejorado'), ('alta_medica', 'Alta Médica'), ('estable', 'Estable'), ('derivado', 'Derivado a Especialista'), ('abandono', 'Abandono de Tratamiento'), ('sin_cambios', 'Sin Cambios Significativos')], max_length=30, null=True, verbose_name='Estado del Paciente al Alta'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='logros_obtenidos',
            field=models.TextField(blank=True, help_text='Objetivos terapéuticos alcanzados durante el tratamiento', null=True, verbose_name='Logros Obtenidos'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='plan_seguimiento',
            field=models.TextField(blank=True, help_text='Plan de seguimiento y controles post-alta', null=True, verbose_name='Plan de Seguimiento'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='recomendaciones_alta',
            field=models.TextField(blank=True, help_text='Indicaciones y recomendaciones para el paciente al finalizar el tratamiento', null=True, verbose_name='Recomendaciones al Alta'),
        ),
        migrations.AddField(
            model_name='sesionkinesica',
            name='resumen_tratamiento',
            field=models.TextField(blank=True, help_text='Resumen de las intervenciones y técnicas aplicadas', null=True, verbose_name='Resumen del Tratamiento'),
        ),
    ]
