# Generated by Django 5.2.15 on 2026-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SesionesKinesicas', '0004_registroescalasesion_quickdash_womac'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registroescalasesion',
            new_name='SesionesKin_pacient_6f4fd7_idx',
            old_name='SesionesKin_pacient_8f0a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='registroescalasesion',
            new_name='SesionesKin_sesion__21aa48_idx',
            old_name='SesionesKin_sesion__a1b3c4_idx',
        ),
    ]
