# Generated by Django 5.2.15 on 2026-07-22 16:32
# Reescrita idempotente.

import django.db.models.deletion
from django.db import migrations, models

from ciclos_clinicos.migration_utils import add_bigint_column_if_missing, column_exists


def apply_sesiones_ciclo_schema(apps, schema_editor):
    for table in ('SesionesKinesicas_registroescalasesion', 'SesionesKinesicas_sesionkinesica'):
        add_bigint_column_if_missing(schema_editor, table, 'ciclo_id', nullable=True)

    with schema_editor.connection.cursor() as cursor:
        for table, col in (
            ('SesionesKinesicas_sesionkinesica', 'ciclo_id'),
            ('SesionesKinesicas_registroescalasesion', 'ciclo_id'),
        ):
            if not column_exists(cursor, table, col):
                continue
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = 'ciclo_id'
                  AND REFERENCED_TABLE_NAME = 'ciclos_clinicos_cicloclinico'
                """,
                [table],
            )
            if cursor.fetchone()[0] == 0:
                schema_editor.execute(
                    f'ALTER TABLE `{table}` ADD CONSTRAINT `{table}_ciclo_id_fk` '
                    f'FOREIGN KEY (`ciclo_id`) REFERENCES `ciclos_clinicos_cicloclinico` (`id`)'
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('Login', '0072_ciclos_clinicos_inicial'),
        ('SesionesKinesicas', '0005_ciclos_clinicos_inicial'),
        ('ciclos_clinicos', '0001_ciclos_clinicos_inicial'),
    ]

    operations = [
        migrations.RunPython(apply_sesiones_ciclo_schema, noop_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='sesionkinesica',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='registroescalasesion',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='registros_escalas_sesion',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
                migrations.AddField(
                    model_name='sesionkinesica',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sesiones_kinesicas',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name='sesionkinesica',
                    unique_together={('ciclo', 'numero_sesion')},
                ),
                migrations.AddIndex(
                    model_name='sesionkinesica',
                    index=models.Index(
                        fields=['ciclo', '-numero_sesion'],
                        name='SesionesKin_ciclo_i_f1b989_idx',
                    ),
                ),
            ],
        ),
    ]
