# Generated by Django 5.2.17 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SesionesKinesicas', '0007_ciclo_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroescalasesion',
            name='tipo_escala',
            field=models.CharField(choices=[('psfs', 'PSFS'), ('groc', 'GROC'), ('eq5d', 'EQ-5D'), ('barthel', 'Barthel'), ('ena', 'ENA'), ('screening', 'Screening Örebro'), ('oswestry', 'Oswestry ODI'), ('lefs', 'LEFS'), ('quickdash', 'QuickDASH'), ('womac', 'WOMAC'), ('tug', 'TUG'), ('berg', 'Berg'), ('tinetti', 'Tinetti')], max_length=20),
        ),
    ]
