# Generated by Django 5.2.17 on 2026-09-15 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0005_add_secretaria_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('individual', 'Individual'), ('clinico_pro', 'Clínico Pro'), ('clinica', 'Clínica / Centro'), ('legacy_full', 'Legacy Full Access')], max_length=30, unique=True, verbose_name='Código del Plan')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Plan')),
                ('max_kinesiologos', models.PositiveIntegerField(default=1, verbose_name='Máximo Kinesiólogos')),
                ('max_pacientes_activos', models.IntegerField(default=100, help_text='-1 para ilimitados', verbose_name='Máximo Pacientes Activos')),
                ('permite_qr_anamnesis', models.BooleanField(default=False, verbose_name='Anamnesis Remota (QR)')),
                ('permite_recetas_digitales', models.BooleanField(default=False, verbose_name='Recetas Médicas Digitales')),
                ('permite_reportes_dss', models.BooleanField(default=False, verbose_name='Reportes DSS & Analítica')),
                ('permite_exportacion_arco', models.BooleanField(default=False, verbose_name='Exportación ARCO (JSON/HTML)')),
                ('permite_auditoria_pdf', models.BooleanField(default=False, verbose_name='Exportación Auditoría PDF')),
                ('permite_multi_seda', models.BooleanField(default=False, verbose_name='Multi-Seda / Migración Pacientes')),
                ('permite_roles_avanzados', models.BooleanField(default=False, verbose_name='Roles Avanzados (Secretaría/Admin)')),
                ('permite_logo_personalizado', models.BooleanField(default=False, verbose_name='Logo Personalizado en Informes')),
                ('permite_dashboard_gerencial', models.BooleanField(default=False, verbose_name='Dashboard Gerencial & Métricas')),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('prueba', 'Prueba Gratuita')], default='activa', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('es_legacy', models.BooleanField(default=False, help_text='Aplica para cuentas iniciales de producción con acceso completo')),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='clinicas.clinica')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='planes.plan')),
            ],
            options={
                'verbose_name': 'Suscripción de Clínica',
                'verbose_name_plural': 'Suscripciones de Clínicas',
            },
        ),
    ]
