# Generated by Django 5.2.17 on 2026-09-15 17:44

from django.db import migrations

def populate_initial_plans(apps, schema_editor):
    Plan = apps.get_model('planes', 'Plan')
    SuscripcionClinica = apps.get_model('planes', 'SuscripcionClinica')
    Clinica = apps.get_model('clinicas', 'Clinica')

    # Crear los 4 planes base
    plan_individual, _ = Plan.objects.get_or_create(
        codigo='individual',
        defaults={
            'nombre': 'Individual',
            'max_kinesiologos': 1,
            'max_pacientes_activos': 100,
        }
    )

    plan_pro, _ = Plan.objects.get_or_create(
        codigo='clinico_pro',
        defaults={
            'nombre': 'Clínico Pro',
            'max_kinesiologos': 2,
            'max_pacientes_activos': -1,
            'permite_qr_anamnesis': True,
            'permite_recetas_digitales': True,
            'permite_reportes_dss': True,
            'permite_exportacion_arco': True,
            'permite_logo_personalizado': True,
        }
    )

    plan_clinica, _ = Plan.objects.get_or_create(
        codigo='clinica',
        defaults={
            'nombre': 'Clínica / Centro',
            'max_kinesiologos': 4,
            'max_pacientes_activos': -1,
            'permite_qr_anamnesis': True,
            'permite_recetas_digitales': True,
            'permite_reportes_dss': True,
            'permite_exportacion_arco': True,
            'permite_auditoria_pdf': True,
            'permite_multi_seda': True,
            'permite_roles_avanzados': True,
            'permite_logo_personalizado': True,
            'permite_dashboard_gerencial': True,
        }
    )

    plan_legacy, _ = Plan.objects.get_or_create(
        codigo='legacy_full',
        defaults={
            'nombre': 'Legacy Full Access',
            'max_kinesiologos': 999,
            'max_pacientes_activos': -1,
            'permite_qr_anamnesis': True,
            'permite_recetas_digitales': True,
            'permite_reportes_dss': True,
            'permite_exportacion_arco': True,
            'permite_auditoria_pdf': True,
            'permite_multi_seda': True,
            'permite_roles_avanzados': True,
            'permite_logo_personalizado': True,
            'permite_dashboard_gerencial': True,
        }
    )

    # Migrar todas las clínicas existentes al plan legacy
    for clinica in Clinica.objects.all():
        SuscripcionClinica.objects.get_or_create(
            clinica=clinica,
            defaults={
                'plan': plan_legacy,
                'estado': 'activa',
                'es_legacy': True,
            }
        )

def reverse_initial_plans(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
        ('clinicas', '0005_add_secretaria_role'),
    ]

    operations = [
        migrations.RunPython(populate_initial_plans, reverse_initial_plans)
    ]
