# Generated by Django 5.2.17 on 2026-09-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_populate_initial_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='permite_gestion_pagos',
            field=models.BooleanField(default=True, verbose_name='Gestión de Pagos & Packs de Atención'),
        ),
    ]
