# Generated by Django 5.2.17 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_add_permite_gestion_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='permite_capacidad_multibox',
            field=models.BooleanField(default=False, verbose_name='Gestión Multi-Box / Capacidad Simultánea'),
        ),
    ]
