# Generated by Django 5.2.17 on 2026-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0005_alter_plan_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='codigo',
            field=models.CharField(choices=[('individual', 'Individual'), ('clinico_pro', 'Clínico Pro'), ('clinica', 'Clínica / Centro'), ('legacy_full', 'Legacy Full Access')], max_length=30, unique=True, verbose_name='Código del Plan'),
        ),
    ]
