# Generated by Django 5.2.17 on 2026-09-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0006_alter_plan_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionclinica',
            name='override_max_adjuntos',
            field=models.PositiveIntegerField(default=0, help_text='0 significa desactivado. Ponle 3 o 5 para habilitar la subida solo a esta clínica en específico.', verbose_name='Máximo de Archivos por Ficha (Excepción)'),
        ),
    ]
