# Generated by Django 5.2.7 on 2026-05-15 00:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0064_paciente_correo_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionOswestry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('seccion_1_intensidad_dolor', models.IntegerField(help_text='0-5: Intensidad del dolor', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_2_estar_de_pie', models.IntegerField(help_text='0-5: Capacidad para estar de pie', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_3_cuidados_personales', models.IntegerField(help_text='0-5: Cuidados personales', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_4_dormir', models.IntegerField(help_text='0-5: Calidad del sueño', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_5_levantar_peso', models.IntegerField(help_text='0-5: Capacidad para levantar peso', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_6_actividad_sexual', models.IntegerField(help_text='0-5: Actividad sexual', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_7_andar', models.IntegerField(help_text='0-5: Capacidad para andar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_8_vida_social', models.IntegerField(help_text='0-5: Vida social', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_9_estar_sentado', models.IntegerField(help_text='0-5: Capacidad para estar sentado', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('seccion_10_viajar', models.IntegerField(help_text='0-5: Capacidad para viajar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('notas_clinicas', models.TextField(blank=True, help_text='Observaciones clínicas adicionales', null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_oswestry', to='Login.clinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_oswestry', to='Login.paciente')),
            ],
            options={
                'verbose_name': 'Evaluación Oswestry',
                'verbose_name_plural': 'Evaluaciones Oswestry',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
