# Generated by Django 5.2.7 on 2026-05-15 00:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0064_paciente_correo_reserva'),
        ('TiposDeFormularios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionLEFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('actividad_1_trabajo', models.IntegerField(help_text='0-4: Trabajo usual, domestico o escuela', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_2_pasatiempos', models.IntegerField(help_text='0-4: Pasatiempos, recreación o deportes', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_3_banio', models.IntegerField(help_text='0-4: Entrar o salir del baño', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_4_andar_cuartos', models.IntegerField(help_text='0-4: Andar entre cuartos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_5_zapatos', models.IntegerField(help_text='0-4: Ponerse zapatos o calcetines', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_6_cuclillas', models.IntegerField(help_text='0-4: Ponerse en cuclillas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_7_levantar_objeto', models.IntegerField(help_text='0-4: Levantar objeto del piso', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_8_actividades_ligeras', models.IntegerField(help_text='0-4: Actividades ligeras domesticas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_9_actividades_pesadas', models.IntegerField(help_text='0-4: Actividades pesadas domesticas', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_10_coche', models.IntegerField(help_text='0-4: Entrar o salir de un coche', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_11_caminar_2cuadras', models.IntegerField(help_text='0-4: Caminar 2 cuadras', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_12_caminar_milla', models.IntegerField(help_text='0-4: Caminar una milla', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_13_escalones', models.IntegerField(help_text='0-4: Subir o bajar 10 escalones', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_14_estar_pie', models.IntegerField(help_text='0-4: Estar de pie por 1 hora', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_15_estar_sentado', models.IntegerField(help_text='0-4: Estar sentado por 1 hora', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_16_correr_plano', models.IntegerField(help_text='0-4: Correr sobre suelo plano', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_17_correr_desigual', models.IntegerField(help_text='0-4: Correr sobre suelo desigual', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_18_vueltas_bruscas', models.IntegerField(help_text='0-4: Hacer vueltas bruscas corriendo', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_19_saltar', models.IntegerField(help_text='0-4: Saltar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('actividad_20_vuelta_cama', models.IntegerField(help_text='0-4: Darse la vuelta en la cama', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('notas_clinicas', models.TextField(blank=True, help_text='Observaciones clínicas adicionales', null=True)),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_lefs', to='Login.clinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_lefs', to='Login.paciente')),
            ],
            options={
                'verbose_name': 'Evaluación LEFS',
                'verbose_name_plural': 'Evaluaciones LEFS',
                'ordering': ['-fecha_evaluacion'],
            },
        ),
    ]
