# Generated by Django 5.2.15 on 2026-07-22 16:32
# Reescrita idempotente.

import django.db.models.deletion
from django.db import migrations, models

from ciclos_clinicos.migration_utils import add_bigint_column_if_missing, column_exists


def apply_tipos_ciclo_schema(apps, schema_editor):
    tables = (
        'TiposDeFormularios_evaluacionlefs',
        'TiposDeFormularios_evaluacionoswestry',
        'TiposDeFormularios_evaluacionquickdash',
        'TiposDeFormularios_evaluacionwomac',
    )
    for table in tables:
        add_bigint_column_if_missing(schema_editor, table, 'ciclo_id', nullable=True)

    with schema_editor.connection.cursor() as cursor:
        for table in tables:
            if not column_exists(cursor, table, 'ciclo_id'):
                continue
            cursor.execute(
                """
                SELECT COUNT(*) FROM information_schema.KEY_COLUMN_USAGE
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = 'ciclo_id'
                  AND REFERENCED_TABLE_NAME = 'ciclos_clinicos_cicloclinico'
                """,
                [table],
            )
            if cursor.fetchone()[0] == 0:
                schema_editor.execute(
                    f'ALTER TABLE `{table}` ADD CONSTRAINT `{table}_ciclo_id_fk` '
                    f'FOREIGN KEY (`ciclo_id`) REFERENCES `ciclos_clinicos_cicloclinico` (`id`)'
                )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('TiposDeFormularios', '0003_evaluacionquickdash_evaluacionwomac'),
        ('ciclos_clinicos', '0001_ciclos_clinicos_inicial'),
    ]

    operations = [
        migrations.RunPython(apply_tipos_ciclo_schema, noop_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='evaluacionlefs',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_lefs',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
                migrations.AddField(
                    model_name='evaluacionoswestry',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_oswestry',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
                migrations.AddField(
                    model_name='evaluacionquickdash',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_quickdash',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
                migrations.AddField(
                    model_name='evaluacionwomac',
                    name='ciclo',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='evaluaciones_womac',
                        to='ciclos_clinicos.cicloclinico',
                    ),
                ),
            ],
        ),
    ]
