"""
Django settings for ProyectoMainAPP project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables desde .env en desarrollo (el archivo no se commitea)
_env_path = BASE_DIR / '.env'
if _env_path.exists():
    try:
        from dotenv import load_dotenv
        load_dotenv(_env_path)
    except ImportError:
        pass


def _env_bool(key, default=False):
    value = os.environ.get(key)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DEBUG = _env_bool('DJANGO_DEBUG', default=True)

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-change-in-production'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY es obligatorio cuando DJANGO_DEBUG=False')

_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        '.ngrok-free.app',
        'localhost',
        '127.0.0.1',
        'software.kenkomed.cl',
        'www.software.kenkomed.cl',
        'app.kenkomed.cl',
        '*.kenkomed.cl',
        '*.trycloudflare.com',
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'axes',  # Rate limiting / brute-force protection
    'clinicas.apps.ClinicasConfig',
    'clinicos',
    'Login',
    'PanelDeControl',
    'FormularioInicial',
    'TiposDeFormularios',
    'RecetasMedicas',
    'SesionesKinesicas',
    'ciclos_clinicos',
    'planes.apps.PlanesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'PanelDeControl.middleware.NoCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'clinicas.middleware.ClinicaMiddleware',
    'axes.middleware.AxesMiddleware',  # ⚠️ Debe ir último
]

ROOT_URLCONF = 'ProyectoMainAPP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'clinicas.context_processors.clinica_sesion',
                'planes.context_processors.plan_features',
                'PanelDeControl.context_processors.novedades_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'ProyectoMainAPP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'my_database'),
        'USER': os.environ.get('DB_USER', 'django_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'my_password'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'  
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True

# Resend API Settings (Envío por HTTPS API - Inmune a bloqueos VPS/DigitalOcean)
import logging as _logging
_resend_key = os.environ.get('RESEND_API_KEY', '').strip()
if not _resend_key:
    if DEBUG:
        _logging.getLogger(__name__).warning(
            'RESEND_API_KEY no está configurada. Los correos no se enviarán en modo desarrollo.'
        )
    else:
        raise ImproperlyConfigured('RESEND_API_KEY es obligatoria en producción. Configúrala en el .env o en las variables de entorno del servidor.')
RESEND_API_KEY = _resend_key

_resend_from = os.environ.get('RESEND_FROM_EMAIL', '').strip()
if not _resend_from:
    _resend_from = 'KenkoMed <notificaciones@kenkomed.cl>'
RESEND_FROM_EMAIL = _resend_from







# Email Settings (Resend HTTPS Backend por defecto, inmune a bloqueos VPS)
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'ProyectoMainAPP.resend_backend.ResendEmailBackend')

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', default=False)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 10))

# Credenciales de producción
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')


# Remitente visible formateado para prevenir rechazo DMARC/SPF
_default_from = os.environ.get('DEFAULT_FROM_EMAIL', '')
if _default_from:
    DEFAULT_FROM_EMAIL = _default_from
elif EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = f'KenkoMed <{EMAIL_HOST_USER}>'
else:
    DEFAULT_FROM_EMAIL = 'KenkoMed <kenkomedplus@gmail.com>'

# Copia oculta por defecto para auditoría del sistema
EMAIL_BCC_SYSTEM = os.environ.get('EMAIL_BCC_SYSTEM', EMAIL_HOST_USER or 'kenkomedplus@gmail.com')




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

_csrf_origins = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://2695-2803-c600-8104-8392-89f9-6098-6dd5-84db.ngrok-free.app',
        'https://*.ngrok-free.app',
        'https://software.kenkomed.cl',
        'https://www.software.kenkomed.cl',
        'https://app.kenkomed.cl',
        'https://*.kenkomed.cl',
        'https://*.trycloudflare.com',
    ]

CSRF_FAILURE_VIEW = 'ProyectoMainAPP.error_handlers.csrf_failure'

# Seguridad en producción (HTTPS). En local/Docker sin TLS: SECURE_SSL_REDIRECT=False en .env
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = _env_bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = _env_bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies de sesión — Explícitas para evitar sobreescrituras accidentales
SESSION_COOKIE_HTTPONLY = True      # Protege contra robo de cookies vía XSS
SESSION_COOKIE_SAMESITE = 'Lax'    # Protege contra CSRF cross-site

# ─── django-axes: Protección contra fuerza bruta en login ─────────────────────
# Bloquea la combinación de Usuario + IP tras AXES_FAILURE_LIMIT intentos fallidos.
# En desarrollo local (DEBUG=True) se desactiva para evitar bloqueos durante pruebas. En producción (DEBUG=False) estará siempre ACTIVO.
AXES_ENABLED = _env_bool('AXES_ENABLED', default=not DEBUG)
AXES_FAILURE_LIMIT = int(os.environ.get('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = int(os.environ.get('AXES_COOLOFF_HOURS', '1'))  # horas
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]  # Bloqueo por usuario + IP
AXES_RESET_ON_SUCCESS = True                    # Reinicia contador tras login exitoso
AXES_IPWARE_PROXY_COUNT = 1                     # Permite obtener la IP real del cliente tras el proxy Nginx
AXES_LOCKOUT_TEMPLATE = None                    # Usa la respuesta de la vista de login
AXES_VERBOSE = False                            # Sin spam de logs
# Usa el backend de base de datos para persistir bloqueos entre reinicios
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

