# Generated by Django 5.2.15 on 2026-06-18 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0064_paciente_correo_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut_empresa', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('individual', 'Profesional Individual'), ('clinica', 'Clínica / Centro')], default='individual', max_length=20)),
                ('max_clinicos', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, choices=[('admin', 'Administrador de Clínica'), ('miembro', 'Miembro')], default='miembro', max_length=20, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='clinicas.clinica')),
                ('clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='Login.clinico')),
            ],
            options={
                'unique_together': {('clinico', 'clinica')},
            },
        ),
    ]
