# Generated by Django 5.2.15 on 2026-06-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0002_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaclinica',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador de Clínica'), ('miembro', 'Miembro')], max_length=20, null=True),
        ),
    ]
