# Generated by Django 5.2.15 on 2026-06-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0003_alter_membresiaclinica_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='logo',
            field=models.ImageField(blank=True, help_text='Se usa en correos e informes. Si no hay logo, se muestra KenkoMed.', null=True, upload_to='clinicas/logos/', verbose_name='Logo del centro'),
        ),
    ]
