# Generated by Django 5.2.17 on 2026-09-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0004_clinica_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiaclinica',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador de Clínica'), ('miembro', 'Miembro'), ('secretaria', 'Secretaria / Recepción')], max_length=20, null=True),
        ),
    ]
