# Generated by Django 5.2.17 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicas', '0005_add_secretaria_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='capacidad_simultanea',
            field=models.PositiveIntegerField(default=1, verbose_name='Capacidad de Boxes Simultáneos'),
        ),
    ]
