# Generated by Django 5.2.15 on 2026-07-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Login', '0071_ciclos_clinicos_inicial'),
        ('clinicas', '0004_clinica_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ciclo', models.PositiveIntegerField(verbose_name='Número de ciclo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('abandonado', 'Abandonado')], default='activo', max_length=20)),
                ('motivo_consulta', models.TextField(blank=True, default='')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas_cierre', models.TextField(blank=True, default='')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_clinicos', to='clinicas.clinica')),
                ('clinico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_a_cargo', to='Login.clinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_clinicos', to='Login.paciente')),
            ],
            options={
                'verbose_name': 'Ciclo clínico',
                'verbose_name_plural': 'Ciclos clínicos',
                'ordering': ['-numero_ciclo'],
                'indexes': [models.Index(fields=['paciente', 'estado'], name='ciclos_clin_pacient_a2030f_idx'), models.Index(fields=['clinica', '-fecha_inicio'], name='ciclos_clin_clinica_7d9255_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activo')), fields=('paciente', 'clinica'), name='unico_ciclo_activo_por_paciente_clinica')],
                'unique_together': {('paciente', 'clinica', 'numero_ciclo')},
            },
        ),
    ]
