# Generated by Django 5.2.17 on 2026-09-24 17:53

import ciclos_clinicos.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos_clinicos', '0002_backfill_ciclos_existentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoHistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=ciclos_clinicos.models.path_adjunto_historial, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('peso_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='ciclos_clinicos.cicloclinico')),
            ],
            options={
                'verbose_name': 'Adjunto de Historial Clínico',
                'verbose_name_plural': 'Adjuntos de Historial Clínico',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
